name: CI Fedora

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: fedora

    steps:

    - name: Install additional packages
      run: dnf -y install autoconf automake awk boost-devel doxygen gcc-c++ gettext glibc-langpack-de glibc-langpack-fr glibc-langpack-en graphviz json-c-devel libtool libxml2-devel make python3-devel ruby-devel rubygem-test-unit swig xz

    - name: List installed packages
      run: rpm -qa | sort

    - name: Git checkout
      uses: actions/checkout@v1

    - name: Configure
      run: make -f Makefile.repo

    - name: Compile
      run: make -j 2

    - name: Install
      run: make install

    - name: Run unit tests
      run: make -j 2 check VERBOSE=1

    - name: Make package
      run: make package
