# Configure via .codespellrc in the root of the project
---
name: Codespell

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        # third-party so better use commit shasum (here of v2)
        uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461
